version: 1

services:
  backend:
    name: fastapi-backend
    type: http
    context: /api
    port: 8000
    networkVisibility: Public
    build:
      path: backend  # Backend folder where FastAPI code is located
      command: uvicorn main:app --host 0.0.0.0 --port 8000
    env:
      - name: YOUTUBE_API_KEY
        value: "AIzaSyAmt734ugZJiigg7C3VAzZLLJ3iKR1GrHc"
      - name: TOGETHER_AI_API_KEY
        value: "8b283a377efef633e1ca5ab57de868d6ac25b1af08c8ecd7a2b41a79ede116ef"
      - name: GOOGLE_API_KEY
        value: "AIzaSyAmt734ugZJiigg7C3VAzZLLJ3iKR1GrHc"
      - name: GOOGLE_CSE_ID
        value: "734a723e5c2d64e81"
    scale:
      min: 1
      max: 3

  frontend:
    name: react-frontend
    type: static
    context: /
    build:
      path: frontend  # Frontend folder where React app is located
      command: npm run build
    routes:
      - path: /
        target: /
    scale:
      min: 1
      max: 3
